site_name: Vaibhav Notes
site_url: https://vaibhav3209.github.io/vaibhav_notes/
repo_url: https://github.com/vaibhav3209/vaibhav_notes
use_directory_urls: false

theme:
  name: material

  icon:
    repo: fontawesome/brands/github

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.sections
    - navigation.expand
    - content.code.copy


extra_css:
  - stylesheets/extra.css


extra_javascript:
  - javascripts/note-collapse.js

markdown_extensions:
  - md_in_html
  - attr_list       # to refer css atributes like {.back to list}
  - tables
  - admonition      # for !!! tip, !!! question
  - pymdownx.details
  - pymdownx.tabbed:
        alternate_style: true
  - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format


nav:
  - Home: index.md
  - SQL:
      - NULL Semantics: topics/sql/null_semantics.md
      - Leetcode + Concepts: topics/sql/leetcode_sql.md
  - DVER: topics/DVER/First_MDT.md
  - EEDM: topics/EEDM/First_MDT.md
