site_name: Vaibhav Notes
site_url: https://vaibhav3209.github.io/vaibhav_notes/
repo_url: https://github.com/vaibhav3209/vaibhav_notes
use_directory_urls: false

theme:
  name: material

  icon:
    repo: fontawesome/brands/github

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.sections
    - navigation.expand
    - content.code.copy


extra_css:
  - stylesheets/extra.css


extra_javascript:
  - javascripts/note-collapse.js

markdown_extensions:
  - md_in_html
  - attr_list       # to refer css atributes like {.back to list}
  - tables
  - admonition      # for !!! tip, !!! question
  - pymdownx.details
  - pymdownx.tasklist:      # For Todo checkboxes
        custom_checkbox: true
  - pymdownx.tabbed:
        alternate_style: true
  - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format


nav:
  - Home: index.md

  - SQL:
      - Clauses:
          - Select: topics/SQL/Select.md
#          - From: topics/SQL/From.md
          - Where: topics/SQL/Where.md
          - With: topics/SQL/With.md
          - Group By: topics/SQL/GroupBy.md
          - Having: topics/SQL/Having.md

      - NULL Semantics: topics/SQL/NullSemantics.md
      - Difference: topics/SQL/DifferenceBetween.md
      - Leetcode List: topics/SQL/LeetcodeList.md
      - Interview Questions: topics/SQL/InterviewTheory.md
      - SQL Coding Questions: topics/SQL/InterviewCoding.md

  - DSA:
      - LinkedList: topics/DSA/LinkedList/

  - Python:
      - OOP: topics/Python/OOP/

  - DVER: topics/DVER/First_MDT.md

  - EEDM: topics/EEDM/First_MDT.md

  - Resume Tips: topics/Interviews/Resume.md

  - Spark:
    - Introduction: topics/Spark/Introduction.md
    - Architechture: topics/Spark/Architechture.md