site_name: Vaibhav Notes
site_url: ""
use_directory_urls: false

#................................
# Themes Available (that are good but require different setup)
#     name: material
#     name: readthedocs
#     name: simple-blog
#     name: torillic
#................................
theme:
  name: torillic
  features:
    - navigation.sections
    - navigation.expand
    - content.code.copy
    -

extra_css:
  - stylesheets/extra.css


extra_javascript:
  - javascripts/pagination.js
  - https://cdnjs.cloudflare.com/ajax/libs/mermaid/10.9.0/mermaid.min.js
  - javascripts/mermaid-init.js

markdown_extensions:
  - md_in_html
  - attr_list
  - tables
  - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format

hooks:
  - hooks/notes_hooks.py

nav:
  - Home: index.md
  - SQL:  topics/sql/index.md
  - DVER: topics/DVER/First_MDT.md
  - EEDM: topics/EEDM/First_MDT.md
